jobs:
    
  

  - name: ac-inrunSh301
    type: runSh
    steps:
      - IN: ac-samplescript301
      - TASK:
        - script: ./IN/ar-samplescript301/gitRepo/echo.sh
        
  - name: ac-inrunCLI301
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        
  - name: ac-inrunCLI302
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        
  
        
  - name: ac-inrunCLI303
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        

        
  - name: ac-inrunCLI304
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        
 
        
  - name: ac-inrunCLI305
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
  
        
  - name: ac-inrunCLI306
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        
 
  - name: ac-inrunCLI307
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
 
        
  - name: ac-inrunCLI308
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
  
  - name: ac-inrunCLI309
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        
  - name: ac-inrunCLI310
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        
  - name: ac-inrunSh302
    type: runSh
    steps:
      - IN: ac-samplescript302
      - TASK:
        - script: ./IN/ac-samplescript302/gitRepo/echo.sh
        
  - name: ac-inrunSh303
    type: runSh
    steps:
      - IN: ac-samplescript303
      - IN: ac-inrunSh302
      - TASK:
        - script: ./IN/ac-samplescript303/gitRepo/echo.sh
 
  - name: ac-inrunSh304
    type: runSh
    steps:
      - IN: ac-samplescript304
      - IN: ac-inrunSh303
      - TASK:
        - script: ./IN/ac-samplescript304/gitRepo/echo.sh
  
  - name: ac-inrunSh305
    type: runSh
    steps:
      - IN: ac-samplescript305
      - IN: ac-inrunSh304
      - TASK:
        - script: ./IN/ac-samplescript305/gitRepo/echo.sh
        
  - name: ac-inrunSh306
    type: runSh
    steps:
      - IN: ac-samplescript306
      - IN: ac-inrunSh305
      - TASK:
        - script: ./IN/ac-samplescript306/gitRepo/echo.sh
        
  - name: ac-inrunSh307
    type: runSh
    steps:
      - IN: ac-samplescript307
      - IN: ac-inrunSh306
      - TASK:
        - script: ./IN/ac-samplescript307/gitRepo/echo.sh
        
  - name: ac-inrunSh308
    type: runSh
    steps:
      - IN: ac-samplescript308
      - IN: ac-inrunSh307
      - TASK:
        - script: ./IN/ac-samplescript308/gitRepo/echo.sh
        
  - name: ac-inrunSh309
    type: runSh
    steps:
      - IN: ac-samplescript309
      - IN: ac-inrunSh308
      - TASK:
        - script: ./IN/ac-samplescript309/gitRepo/echo.sh
        
  - name: ac-inrunSh310
    type: runSh
    steps:
      - IN: ac-samplescript310
      - IN: ac-inrunSh309
      - TASK:
        - script: ./IN/ac-samplescript310/gitRepo/echo.sh
        