jobs:


  - name: ac-inrunSh301
    type: runSh
    steps:
      - IN: ac-samplescript301
      - TASK:
        - script: ./IN/ac-samplescript301/gitRepo/echo.sh
        
  - name: ac-inrunCLI301
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        
  - name: ac-inrunCLI302
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls   
        
  - name: ac-inrunCLI303
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        
  - name: ac-inrunCLI304
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls    
        
  - name: ac-inrunCLI305
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls  
        
  - name: ac-inrunCLI306
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
 
  - name: ac-inrunCLI307
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
 
        
  - name: ac-inrunCLI308
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
  
  - name: ac-inrunCLI309
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        
  - name: ac-inrunCLI310
    type: runCLI
    steps:
      - IN: ac-inrunSh301
      - TASK:
        - script: ls
        
  - name: ac-inrunSh302
    type: runSh
    steps:
      - IN: ac-samplescript302
      - TASK:
        - script: ./IN/ac-samplescript302/gitRepo/echo.sh
        
  - name: ac-inrunSh303
    type: runSh
    steps:
      - IN: ac-samplescript303
      - IN: ac-inrunSh302
      - TASK:
        - script: ./IN/ac-samplescript303/gitRepo/echo.sh
 
  - name: ac-inrunSh304
    type: runSh
    steps:
      - IN: ac-samplescript304
      - IN: ac-inrunSh303
      - TASK:
        - script: ./IN/ac-samplescript304/gitRepo/echo.sh
  
  - name: ac-inrunSh305
    type: runSh
    steps:
      - IN: ac-samplescript305
      - IN: ac-inrunSh304
      - TASK:
        - script: ./IN/ac-samplescript305/gitRepo/echo.sh
        
  - name: ac-inrunSh306
    type: runSh
    steps:
      - IN: ac-samplescript306
      - IN: ac-inrunSh305
      - TASK:
        - script: ./IN/ac-samplescript306/gitRepo/echo.sh
        
  - name: ac-inrunSh307
    type: runSh
    steps:
      - IN: ac-samplescript307
      - IN: ac-inrunSh306
      - TASK:
        - script: ./IN/ac-samplescript307/gitRepo/echo.sh
        
  - name: ac-inrunSh308
    type: runSh
    steps:
      - IN: ac-samplescript308
      - IN: ac-inrunSh307
      - TASK:
        - script: ./IN/ac-samplescript308/gitRepo/echo.sh
        
  - name: ac-inrunSh309
    type: runSh
    steps:
      - IN: ac-samplescript309
      - IN: ac-inrunSh308
      - TASK:
        - script: ./IN/ac-samplescript309/gitRepo/echo.sh
        
  - name: ac-inrunSh310
    type: runSh
    steps:
      - IN: ac-samplescript310
      - IN: ac-inrunSh309
      - TASK:
        - script: ./IN/ac-samplescript310/gitRepo/echo.sh
  
  - name: ac-inrunSh311
    type: runSh
    steps:
      - IN: ac-samplescript311
      - TASK:
        - script: ./IN/ac-samplescript311/gitRepo/echo.sh
        
  - name: ac-inrunSh312
    type: runSh
    steps:
      - IN: ac-samplescript312
      - IN: ac-inrunSh311
      - TASK:
        - script: ./IN/ac-samplescript312/gitRepo/echo.sh
        
  - name: ac-inrunSh313
    type: runSh
    steps:
      - IN: ac-samplescript313
      - IN: ac-inrunSh311
      - TASK:
        - script: ./IN/ac-samplescript313/gitRepo/echo.sh
 
  - name: ac-inrunSh314
    type: runSh
    steps:
      - IN: ac-samplescript314
      - IN: ac-inrunSh312
      - TASK:
        - script: ./IN/ac-samplescript314/gitRepo/echo.sh
  
  - name: ac-inrunSh315
    type: runSh
    steps:
      - IN: ac-samplescript315
      - IN: ac-inrunSh312
      - TASK:
        - script: ./IN/ac-samplescript315/gitRepo/echo.sh
        
  - name: ac-inrunSh316
    type: runSh
    steps:
      - IN: ac-samplescript316
      - IN: ac-inrunSh313
      - TASK:
        - script: ./IN/ac-samplescript316/gitRepo/echo.sh
        
  - name: ac-inrunSh317
    type: runSh
    steps:
      - IN: ac-samplescript317
      - IN: ac-inrunSh313
      - TASK:
        - script: ./IN/ac-samplescript317/gitRepo/echo.sh
        
  - name: ac-inrunSh318
    type: runSh
    steps:
      - IN: ac-samplescript318
      - IN: ac-inrunSh314
      - TASK:
        - script: ./IN/ac-samplescript318/gitRepo/echo.sh
        
  - name: ac-inrunSh319
    type: runSh
    steps:
      - IN: ac-samplescript319
      - IN: ac-inrunSh314
      - TASK:
        - script: ./IN/ac-samplescript319/gitRepo/echo.sh
        
  - name: ac-inrunSh320
    type: runSh
    steps:
      - IN: ac-samplescript320
      - IN: ac-inrunSh315
      - TASK:
        - script: ./IN/ac-samplescript320/gitRepo/echo.sh
  
  - name: ac-inrunSh321
    type: runSh
    steps:
      - IN: ac-samplescript321
      - IN: ac-inrunSh315
      - TASK:
        - script: ./IN/ac-samplescript321/gitRepo/echo.sh
        
  - name: ac-inrunSh322
    type: runSh
    steps:
      - IN: ac-samplescript322
      - IN: ac-inrunSh316
      - TASK:
        - script: ./IN/ac-samplescript322/gitRepo/echo.sh
        
  - name: ac-inrunSh323
    type: runSh
    steps:
      - IN: ac-samplescript323
      - IN: ac-inrunSh316
      - TASK:
        - script: ./IN/ac-samplescript323/gitRepo/echo.sh
        
  - name: ac-inrunSh324
    type: runSh
    steps:
      - IN: ac-samplescript324
      - IN: ac-inrunSh317
      - TASK:
        - script: ./IN/ac-samplescript324/gitRepo/echo.sh
 
  - name: ac-inrunSh325
    type: runSh
    steps:
      - IN: ac-samplescript325
      - IN: ac-inrunSh317
      - TASK:
        - script: ./IN/ac-samplescript325/gitRepo/echo.sh
  
  - name: ac-inrunSh326
    type: runSh
    steps:
      - IN: ac-samplescript326
      - IN: ac-inrunSh334
      - TASK:
        - script: ./IN/ac-samplescript326/gitRepo/echo.sh
  
  - name: ac-inrunSh327
    type: runSh
    steps:
      - IN: ac-samplescript327
      - IN: ac-inrunSh334
      - TASK:
        - script: ./IN/ac-samplescript327/gitRepo/echo.sh
  
  - name: ac-inrunSh328
    type: runSh
    steps:
      - IN: ac-samplescript328
      - IN: ac-inrunSh335
      - TASK:
        - script: ./IN/ac-samplescript328/gitRepo/echo.sh
  
  - name: ac-inrunSh329
    type: runSh
    steps:
      - IN: ac-samplescript329
      - IN: ac-inrunSh335
      - TASK:
        - script: ./IN/ac-samplescript329/gitRepo/echo.sh
        
  - name: ac-inrunSh330
    type: runSh
    steps:
      - IN: ac-samplescript330
      - IN: ac-inrunSh336
      - TASK:
        - script: ./IN/ac-samplescript330/gitRepo/echo.sh
        
  - name: ac-inrunSh331
    type: runSh
    steps:
      - IN: ac-samplescript331
      - IN: ac-inrunSh336
      - TASK:
        - script: ./IN/ac-samplescript331/gitRepo/echo.sh
        
  - name: ac-inrunSh332
    type: runSh
    steps:
      - IN: ac-samplescript332
      - IN: ac-inrunSh337
      - TASK:
        - script: ./IN/ac-samplescript332/gitRepo/echo.sh
        
  - name: ac-inrunSh333
    type: runSh
    steps:
      - IN: ac-samplescript333
      - IN: ac-inrunSh337
      - TASK:
        - script: ./IN/ac-samplescript333/gitRepo/echo.sh
        
  - name: ac-inrunSh334
    type: runSh
    steps:
      - IN: ac-samplescript334
      - IN: ac-inrunSh338
      - TASK:
        - script: ./IN/ac-samplescript334/gitRepo/echo.sh
        
  - name: ac-inrunSh335
    type: runSh
    steps:
      - IN: ac-samplescript335
      - IN: ac-inrunSh338
      - TASK:
        - script: ./IN/ac-samplescript335/gitRepo/echo.sh
        
  - name: ac-inrunSh336
    type: runSh
    steps:
      - IN: ac-samplescript336
      - IN: ac-inrunSh339
      - TASK:
        - script: ./IN/ac-samplescript336/gitRepo/echo.sh
        
  - name: ac-inrunSh337
    type: runSh
    steps:
      - IN: ac-samplescript337
      - IN: ac-inrunSh339
      - TASK:
        - script: ./IN/ac-samplescript337/gitRepo/echo.sh
  
  - name: ac-inrunSh338
    type: runSh
    steps:
      - IN: ac-samplescript338
      - IN: ac-inrunSh340
      - TASK:
        - script: ./IN/ac-samplescript338/gitRepo/echo.sh
        
  - name: ac-inrunSh339
    type: runSh
    steps:
      - IN: ac-samplescript339
      - IN: ac-inrunSh340
      - TASK:
        - script: ./IN/ac-samplescript339/gitRepo/echo.sh
        
  - name: ac-inrunSh340
    type: runSh
    steps:
      - IN: ac-samplescript340
      - TASK:
        - script: ./IN/ac-samplescript340/gitRepo/echo.sh
